name: CICD for EC@ server
 
on:
  push:
    branches:
        - main
     

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
         cache: "npm"
      - name: npm install and build
        run: |
          yarn install
          yarn build
          cd build && yarn install
          cd build && pm2 restart src/app.js
#         env: 
#           CI: true   


#   depoly:
#     needs: [build]
#     runs-on: ubuntu-latest

#     steps:
#      - name: SSH deploy
#        uses: appleboy/ssh-action@master
#        with:
#           host: ${{ secrets.HOST }}
#           username:  ${{ secrets.USER }}
#           key:  ${{ secrets.KEY }}
#           port:  ${{ secrets.PORT }}
#           script: |
#               # curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
#               # . ~/.nvm/nvm.sh
#               #  nvm instal 14
#               #  npm install -g pm2
#                cd ~/express-mongo-api
#                git pull origin main
#                yarn install
#                yarn build
#                cd build
#                pm2 restart src/app.js
            
            
